import {e,eur,num,pct,date,month,sign,hours,value,metric,table,bars,node} from '../ui/format.js';
import {plot} from '../ui/charts.js';
export const id='datenqualitaet';
export const title='Datenqualität & Methodik';
export function render(data,period) {
const p=data.periods[period];

const c=p.checks, g=data.checks;
return node(`<details open><summary>Prüfergebnisse im gewählten Zeitraum</summary>${table(['Prüfung','Ergebnis'],[['Exportzeilen',num(c.rows)],['Trades ohne Gebühr',num(c.missing_fee_trades)+' · '+pct(c.missing_fee_percent)],['Verkäufe mit Mengen ohne Kauf-Lot',num(c.unmatched_sales)],['Erlös ohne Kauf-Lot',eur(c.unmatched_volume)],['Kurs × Stückzahl auffällig',num(c.price_mismatches)+' Zeilen; gebuchte Beträge maßgeblich'],['Bilanzdifferenz',eur(p.capital.balance_difference)],['Leak-Check',g.leak_check==='passed'?'Bestanden':'Nicht bestätigt'],['Entfernte Duplikate (Gesamt)',num(g.duplicates_removed)],['Datumsabweichungen korrigiert (Gesamt)',num(g.date_mismatches_corrected)],['Zeitraum',date(p.start)+' – '+date(p.end)],['Zeitzone','Europe/Berlin']])}<h3>Zeilen je Typ</h3>${table(['Typ','Anzahl'],Object.entries(c.rows_by_type).map(([k,v])=>[e(k),num(v)]))}</details><details><summary>Buchungslogik und Grenzen</summary><p>${e(data.metadata.methodology)}</p><p>${e(g.tax_evidence)}</p><p>Im gesamten Export stimmen ${num(g.amount_matches_quantity_price_rows)} Handelszeilen innerhalb von 0,011 € mit Stückzahl × Kurs überein. Sechs Commerzbank-Kurse sind um Faktor 1.000 skaliert; eine weitere Kleinbetragszeile weicht geringfügig ab. Der berechnete Schluss-Cash-Saldo ist ${eur(g.cash_balance)}. Ein unabhängiger Cash-Abgleich ist ohne Kontoauszug nicht möglich.</p><ul>${data.metadata.limits.map(s=>`<li>${e(s)}</li>`).join('')}</ul><p>Der Gebühren-Leeranteil bezeichnet leere Exportfelder, keine geschätzten Kosten. Daten enthalten ausschließlich anonyme IDs und öffentliche Instrumentnamen. Cash-Transfers enthalten nur Datum, Richtung und Betrag.</p></details>${c.unmatched_details.length?`<details><summary>Verkäufe ohne Kauf-Lot</summary>${table(['Datum','Instrument','Menge','Erlös'],c.unmatched_details.map(t=>[date(t.date),e(t.name),num(t.shares),eur(t.proceeds)]))}</details>`:''}`);

}
