import {e,eur,num,pct,date,month,sign,hours,value,metric,table,bars,node} from '../ui/format.js';
import {plot} from '../ui/charts.js';
export const id='kapital_bilanz';
export const title='Kapital & Bilanz';
export function render(data,period) {
const p=data.periods[period];

const c=p.capital;
return node(`<div class="metrics">${metric('Eingezahlt',c.deposited)}${metric('Ausgezahlt',c.withdrawn)}${metric('Netto eingezahlt',c.net_deposited)}${metric('Ergebnis / Netto-Einzahlung',c.return_on_net_deposit_percent,'pct')}${metric('Umschlagshäufigkeit',c.turnover,'num','Volumen ÷ Netto-Einzahlung')}${metric('Berechnetes Cash am Ende',c.cash_end)}</div><p class="small">Der Renditequotient berücksichtigt den Zeitpunkt der Einzahlungen nicht. Bei Netto-Einzahlung ≤ 0 ist er nicht definiert. Cash ist aus Buchungen rekonstruiert, ohne unabhängigen Kontoauszug.</p><div class="balance-box"><h3>Bilanz-Check</h3><p>Cash-Veränderung + Veränderung des offenen Einstands inkl. Kaufgebühren − Netto-Einzahlung</p><strong>${eur(c.cash_end-c.cash_start)} + ${eur(c.open_cost_end-c.open_cost_start)} − ${eur(c.net_deposited)} = ${eur(c.balance_lhs)}</strong><div class="accounting-line"><span>Berechnetes Ergebnis <strong>${eur(p.core.result)}</strong></span><span>Differenz <strong>${eur(c.balance_difference)}</strong></span></div><p class="small">${Math.abs(c.balance_difference)<.01?'Die Rechnung stimmt auf Cent-Niveau.':'Differenz aus Verkäufen ohne Anfangs-Lot: '+eur(c.unmatched_effect)+'. Unerklärter Rest: '+eur(c.unexplained_difference)+'.'} Bei Gesamt sind Anfangs-Cash und Anfangsbestand als null angesetzt; vorhandene Verkäufe ohne Kauf werden gesondert korrigiert. Bei Teilzeiträumen werden die Bestände vor Periodenbeginn berücksichtigt.</p></div><h3>Offene Positionen am Periodenende</h3>${table(['Instrument','Stückzahl','Einstand inkl. Gebühren','Bewertung','Unrealisiert'],c.positions.map(s=>[`${e(s.name)}<span class="small block">${e(s.isin)}</span>`,num(s.shares),eur(s.cost_including_fees),s.market_value==null?'Nicht bewertet':eur(s.market_value),s.unrealized==null?'Nicht ermittelbar':eur(s.unrealized)]))}<p class="small">${c.unrealized==null?'Ohne vollständige Kursdaten wird kein unrealisierter Gewinn und kein Gesamtdepotwert berechnet.':'Zusätzlicher unrealisierter Gewinn mit bereitgestellten Kursen: '+eur(c.unrealized)+'.'} Einstand vor Kaufgebühren: ${eur(c.positions.reduce((a,s)=>a+s.cost,0))}.</p>`);

}
