import {e,eur,num,pct,date,month,sign,hours,value,metric,table,bars,node} from '../ui/format.js';
import {plot} from '../ui/charts.js';
export const id='volumen';
export const title='Volumen & Monatsübersicht';
export function render(data,period) {
const p=data.periods[period];

const months=data.months.filter(k=>period==='all'||k.startsWith(period.slice(0,4)));const dates=months.map(k=>k+'-01');
return node(`<div class="metrics">${metric('Kaufvolumen',p.core.buy_volume)}${metric('Verkaufsvolumen',p.core.sell_volume)}${metric('Käufe / Verkäufe',p.core.buy_orders,'num',num(p.core.sell_orders)+' Verkäufe')}</div><button class="overview-total" data-set-period="all"><span>Gesamter Zeitraum</span><strong>${eur(data.periods.all.core.total_volume)}</strong><span>${num(data.periods.all.core.orders)} Orders · ${eur(data.periods.all.core.result)} Ergebnis</span><span aria-hidden="true">↗</span></button>${plot('Monatliches Kauf- und Verkaufsvolumen',dates,[{label:'Käufe',values:months.map(k=>data.periods[k].core.buy_volume)},{label:'Verkäufe',values:months.map(k=>data.periods[k].core.sell_volume)}],'bar')}<p class="small">Einen Monat auswählen, um die gesamte Ansicht darauf umzustellen. Die Übersicht zeigt das gewählte Jahr, bei Gesamt alle Monate.</p><div class="month-cards">${months.map(k=>{const m=data.periods[k];return `<button data-set-period="${k}" class="month-card ${period===k?'selected':''}"><span>${e(month(k))}</span><strong class="${sign(m.core.result)}">${eur(m.core.result)}</strong><span class="small">Volumen ${eur(m.core.total_volume)} · ${num(m.core.orders)} Orders</span><span class="small">Gebühren ${eur(m.costs.fees)} · Trefferquote ${pct(m.quality.hit_rate)}</span><span class="small">Kauf ${eur(m.core.buy_volume)} · Verkauf ${eur(m.core.sell_volume)}</span><span class="small">Bester ${m.top.wins[0]?e(m.top.wins[0].name)+' '+eur(m.top.wins[0].net):'—'} · schwächster ${m.top.losses[0]?e(m.top.losses[0].name)+' '+eur(m.top.losses[0].net):'—'}</span></button>`;}).join('')}</div><div class="month-desktop">${table(['Monat','Kauf','Verkauf','Orders','Gebühren','Ergebnis','Trefferquote','Bester Verkauf','Schwächster Verkauf'],months.map(k=>{const m=data.periods[k];return [`<button data-set-period="${k}" class="text-button">${e(month(k))}</button>`,eur(m.core.buy_volume),eur(m.core.sell_volume),num(m.core.orders),eur(m.costs.fees),`<span class="${sign(m.core.result)}">${eur(m.core.result)}</span>`,pct(m.quality.hit_rate),m.top.wins[0]?e(m.top.wins[0].name)+' '+eur(m.top.wins[0].net):'—',m.top.losses[0]?e(m.top.losses[0].name)+' '+eur(m.top.losses[0].net):'—'];}),'Monatsergebnisse nach Gebühren, Erträgen und Steuern')}</div>`);

}
