import {date,month,e,eur,pct} from './ui/format.js';
import {mountPlots} from './ui/charts.js';
import {animate} from './ui/animations.js';
const $=s=>document.querySelector(s);
const aliases={core:'kernzahlen',fees:'kosten'};
const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);}catch{}}};
let summary,config,features,modules=[],selected=[],period='all',mode='all',dispose=()=>{},disposeAnimations=()=>{};
let theme=storage.get('edgar-theme')||'system';
const media=matchMedia('(prefers-color-scheme: dark)');
function applyTheme(){document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;$('#theme').setAttribute('aria-label','Farbmodus wechseln; aktuell '+(document.documentElement.dataset.theme==='dark'?'dunkel':'hell'));}
applyTheme();
media.addEventListener('change',()=>{applyTheme();if(summary)render();});
$('#theme').addEventListener('click',()=>{theme=document.documentElement.dataset.theme==='dark'?'light':'dark';storage.set('edgar-theme',theme);applyTheme();if(summary)render();});
function fromHash(){const params=new URLSearchParams(location.hash.slice(1));if(params.has('modules'))selected=[...new Set(params.get('modules').split(',').map(x=>aliases[x]||x))].filter(x=>modules.some(m=>m.id===x));if(summary.periods[params.get('period')])period=params.get('period');mode=period==='all'?'all':period.length===4?'year':'month';}
function persist(){storage.set('edgar-modules',JSON.stringify(selected));const hash='modules='+selected.join(',')+'&period='+period;try{history.replaceState(null,'','#'+hash);}catch{};}
function switchControls(){document.querySelectorAll('[data-period-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.periodMode===mode)));const keys=mode==='all'?['all']:mode==='year'?summary.years:summary.months;$('#period').innerHTML=keys.map(k=>`<option value="${k}" ${period===k?'selected':''}>${k==='all'?'Gesamter Zeitraum':k.length===4?k:e(month(k))}</option>`).join('');$('#period').disabled=mode==='all';const idx=keys.indexOf(period);$('#previous').disabled=idx<=0;$('#next').disabled=idx<0||idx===keys.length-1;const p=summary.periods[period];$('#period-label').textContent=date(p.start)+' – '+date(p.end);}
function drawSwitches(){const focusValue=document.activeElement?.closest('#feature-switches')?document.activeElement.value:null;const container=$('#feature-switches');container.innerHTML=modules.map(m=>`<label class="feature-switch"><span>${e(m.title)}</span><input type="checkbox" value="${m.id}" ${selected.includes(m.id)?'checked':''}><span class="switch-track" aria-hidden="true"></span></label>`).join('');if(focusValue){const target=[...container.querySelectorAll('input')].find(input=>input.value===focusValue);target?.focus({preventScroll:true});}}
function setupScenario(p){const input=$('#spread');if(!input)return;const defaultSpread=Number(config.spread_default_percent);input.value=String(Number.isFinite(defaultSpread)?Math.max(0,Math.min(.3,defaultSpread)):0);function update(){const assumption=+input.value;$('#spread-label').textContent=pct(assumption);$('#spread-amount').textContent=eur(p.core.total_volume*assumption/100);$('#spread-combined').textContent=eur(p.broker.visible_fees+p.core.total_volume*assumption/100);input.setAttribute('aria-valuetext',pct(assumption)+' angenommener Spread');}input.addEventListener('input',update);update();}
function render(){dispose();disposeAnimations();const container=$('#modules');container.classList.remove('animate');container.replaceChildren();const p=summary.periods[period];$('#valuation-label').textContent=summary.metadata.prices_provided?'Optionale Nutzerkurse':'Ohne Kursbewertung';modules.filter(m=>selected.includes(m.id)).forEach((m,i)=>{const section=document.createElement('section');section.className='module module-'+m.id;section.id=m.id;section.setAttribute('aria-labelledby',m.id+'-heading');const header=document.createElement('div');header.className='module-heading';const h=document.createElement('h2');h.id=m.id+'-heading';h.textContent=m.title;const n=document.createElement('span');n.className='section-number';n.textContent=String(i+1).padStart(2,'0');header.append(h,n);section.append(header,m.render(summary,period));container.append(section);});switchControls();drawSwitches();$('#status').hidden=selected.length>0;$('#status').textContent=selected.length?'':'Keine Module gewählt. Über „Ansicht anpassen“ kannst du sie einschalten.';dispose=mountPlots(container);setupScenario(p);disposeAnimations=animate(container);persist();}
function setPeriod(k){if(!summary.periods[k])return;period=k;mode=k==='all'?'all':k.length===4?'year':'month';render();}
function navigate(step){const keys=mode==='year'?summary.years:mode==='month'?summary.months:['all'];const idx=keys.indexOf(period);if(keys[idx+step])setPeriod(keys[idx+step]);}
$('#period').addEventListener('change',ev=>setPeriod(ev.target.value));$('#previous').addEventListener('click',()=>navigate(-1));$('#next').addEventListener('click',()=>navigate(1));
document.addEventListener('click',ev=>{const set=ev.target.closest('[data-set-period]');if(set){setPeriod(set.dataset.setPeriod);$('.period-bar').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}const b=ev.target.closest('[data-period-mode]');if(b&&summary){const m=b.dataset.periodMode;setPeriod(m==='all'?'all':m==='year'?(period==='all'?summary.years.at(-1):period.slice(0,4)):(period.length===7?period:summary.months.filter(k=>period==='all'||k.startsWith(period)).at(-1)));}});
let swipeX;$('.period-bar').addEventListener('touchstart',ev=>{if(!ev.target.closest('select,button'))swipeX=ev.touches[0].clientX;},{passive:true});$('.period-bar').addEventListener('touchend',ev=>{if(swipeX!=null){const diff=ev.changedTouches[0].clientX-swipeX;if(Math.abs(diff)>60)navigate(diff<0?1:-1);swipeX=null;}},{passive:true});
const dialog=$('#settings');$('#customize').addEventListener('click',()=>dialog.showModal());$('#close-settings').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',ev=>{if(ev.target===dialog){const rect=dialog.getBoundingClientRect();if(ev.clientX<rect.left||ev.clientX>rect.right||ev.clientY<rect.top||ev.clientY>rect.bottom)dialog.close();}const preset=ev.target.closest('[data-preset]');if(preset){selected=preset.dataset.preset==='all'?modules.map(m=>m.id):preset.dataset.preset==='core'?['kernzahlen']:['trade_republic'];render();}});$('#feature-switches').addEventListener('change',()=>{selected=[...document.querySelectorAll('#feature-switches input:checked')].map(el=>el.value);render();});$('#share').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);$('#share-status').textContent='Ansichtslink kopiert.';}catch{$('#share-status').textContent='Zum Teilen die Adresse aus der Browserzeile kopieren.';}});
addEventListener('hashchange',()=>{if(summary){fromHash();render();}});
async function load(path){const response=await fetch(path,{cache:'no-cache'});if(!response.ok)throw new Error(path+' konnte nicht geladen werden (HTTP '+response.status+').');return response.json();}
try{[summary,config,features]=await Promise.all([load('data/summary.json'),load('config.json'),load('config/features.json')]);if(summary.schema_version!==1||!summary.periods?.all)throw new Error('Das Datenformat ist nicht kompatibel.');modules=await Promise.all(features.map(async feature=>{if(!/^[a-z_]+$/.test(feature.id))throw new Error('Ungültige Modulkonfiguration.');return import('./modules/'+feature.id+'.js');}));selected=features.filter(f=>f.enabled).map(f=>f.id);try{const saved=JSON.parse(storage.get('edgar-modules'));if(Array.isArray(saved))selected=saved.filter(id=>modules.some(m=>m.id===id));}catch{};fromHash();const name=String(config.display_name||'Edgar');const possessive=name.endsWith('s')?name+'’':name+'s';document.title=possessive+' Depot';$('#brand-title').textContent=possessive+' Depot';$('#hero-title').textContent=possessive+' Depot.';$('#footer-title').textContent=possessive+' Depot';if(config.show_age&&Number.isFinite(config.age))$('.intro-meta').append(Object.assign(document.createElement('span'),{textContent:config.age+' Jahre'}));$('#range').textContent=date(summary.periods.all.start)+' – '+date(summary.periods.all.end);render();}catch(error){$('#status').hidden=false;$('#status').classList.add('error');$('#status').textContent='Die Auswertung konnte nicht geladen werden. '+error.message+' Bitte über einen lokalen HTTP-Server oder GitHub Pages öffnen; scripts/analyze.py erzeugt die Datendatei.';$('#customize').disabled=true;console.error(error);}
